name: Format Check

on: [pull_request]

jobs:
  format-check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.1.0
          # This disables running `stylua`
          args: false
      - run: |
          make check
